name: Publish to PyPI

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      force_publish:
        description: 'Force publish to PyPI (use with caution)'
        required: false
        default: false
        type: boolean

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        
    - name: Build package
      run: python -m build
      
    - name: Verify package
      run: |
        twine check dist/*
        python -m pip install dist/*.whl
        python -c "import catalyst_pack_schemas; print(f'Package version: {catalyst_pack_schemas.__version__}')"
        
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        echo "Publishing catalyst-builder to PyPI..."
        twine upload dist/* --verbose
        echo "✅ Successfully published to PyPI"
        
    - name: Create deployment summary
      run: |
        echo "## 🚀 PyPI Deployment Successful" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Package:** catalyst-builder" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** $(python setup.py --version 2>/dev/null || python -c 'import catalyst_pack_schemas; print(catalyst_pack_schemas.__version__)')" >> $GITHUB_STEP_SUMMARY
        echo "**PyPI URL:** https://pypi.org/project/catalyst-builder/" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Next Steps:" >> $GITHUB_STEP_SUMMARY
        echo "1. Update dependent repositories to use new version" >> $GITHUB_STEP_SUMMARY
        echo "2. Test integration across catalyst ecosystem" >> $GITHUB_STEP_SUMMARY
        echo "3. Update documentation with new features" >> $GITHUB_STEP_SUMMARY